---
- name: create and configure virtual machines
  hosts: esxi
  become: true
  roles:
    - role: typical-ha
###not forget to uncomment start all VM in tasks/main.yml
###and change passwords for user astra
- name: configure weservers
  hosts: webservers
  become: true
  tasks:
    - name: install webserver
      include_role:
        name: typical-ha
        tasks_from: install-nginx
########fix /etc/hosts
    - name: copy site content
      copy: 
        src: typical-ha/templates/sites/default/data/ 
        dest: /var/www/html/ 
        owner: www-data
        mode: 0640
    - name: copy second site content
      copy: 
        src: typical-ha/templates/sites/default2/data/ 
        dest: /var/www/html2/
        mode: 0640
    - name: configure site 1
      template: 
        src: typical-ha/templates/sites/default/conf/default.j2
        dest: /etc/nginx/sites-available/default
        mode: 0644
    - name: configure site 2
      template: 
        src: typical-ha/templates/sites/default2/conf/default2.j2
        dest: /etc/nginx/sites-available/default2
        mode: 0644
    - name: Creating a symlink
      ansible.builtin.file:
        src: "/etc/nginx/sites-available/default2"
        dest: "/etc/nginx/sites-enabled/default2"
        state: link
  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted


- name: configure load balancers
  hosts: lb
  become: true
  tasks:
    - name: install load balancer
      include_role:
        name: typical-ha
        tasks_from: install-haproxy
    - name: generate lb config
      template: src=typical-ha/templates/haproxy.j2 dest=/etc/haproxy/haproxy.cfg mode=0644
      notify:
        - restart haproxy
  handlers:
    - name: restart haproxy
      ansible.builtin.service:
        name: haproxy
        state: restarted



- name: set hostname
  hosts: webservers
  become: true
  tasks:
    - name: set hostname
      ansible.builtin.hostname:
        name: "{{ config.name }}"
        use: systemd

- name: set hostname
  hosts: lb
  become: true
  tasks:
    - name: set hostname
      ansible.builtin.hostname:
        name: "{{ config.name }}"
        use: systemd

- name: set hostname
  hosts: dns
  become: true
  tasks:
    - name: set hostname
      ansible.builtin.hostname:
        name: "{{ config.name }}"
        use: systemd
