---
# tasks file for typical-ha
- name: Create a virtual machine on given ESXi hostname
  community.vmware.vmware_guest:
    # This is hostname of particular ESXi server on which user wants VM to be deployed
    esxi_hostname: "{{ esxi_hostname }}"
    hostname: "{{ esxi_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: false
    folder: "{{ store_folder }}"
    name: srv-ha-2
    state: poweredon
    guest_id: otherLinuxGuest
    disk:
    - size_gb: 10
      type: thin
      datastore: "{{ datast }}"
    hardware:
      memory_mb: 512
      num_cpus: 1
      scsi: paravirtual
    networks:
    - name: VM Network
      mac: aa:bb:dd:aa:00:14
#      ip: 10.10.10.100
#      netmask: 255.255.255.0
      device_type: vmxnet3
    wait_for_ip_address: true
    wait_for_ip_address_timeout: 60
  delegate_to: localhost
  register: deploy_vm
